export const EVENT_SHRINK_NAV = 'EVENT_SHRINK_NAV';
export const EVENT_OPEN_NAV = 'EVENT_OPEN_NAV';
export const EVENT_DISPLAY_FILTER_ICONS = 'EVENT_DISPLAY_FILTER_ICONS';
export const EVENT_DISPLAY_FILTER_ICONS_FALSE =
  'EVENT_DISPLAY_FILTER_ICONS_FALSE';
export const OPEN_NOTE = 'OPEN_NOTE';
export const EDIT_DRAFT = 'EDIT_DRAFT';
export const CLOSE_NOTE = 'CLOSE_NOTE';

export const eventBus = new Vue();
